version: '3.7'
services:
  mysql_db_container:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer_container:
    image: adminer:latest
    restart: always
    depends_on:
      - mysql_db_container
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
      ADMINER_DESIGN: galkaev
    ports:
      - "8086:8080"


volumes:
  mysql_db_data_container: